#!/usr/bin/env python3
"""Generate the MusicEvent JSON-LD block from data/events.json + data/venues.json.

Replaces the content between JSON-LD:MUSICEVENT:START and JSON-LD:MUSICEVENT:END
markers in index.html. Run after editing data/events.json or data/venues.json.

Usage:
    python3 tools/events-to-jsonld.py        # writes index.html in place
    python3 tools/events-to-jsonld.py --check # prints diff, exits non-zero if drift

Run from the public repo root.
"""
import json
import re
import sys
from datetime import datetime, date, timedelta
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
EVENTS_PATH = REPO_ROOT / "data" / "events.json"
VENUES_PATH = REPO_ROOT / "data" / "venues.json"
INDEX_PATH = REPO_ROOT / "index.html"
SITE_URL = "https://www.boloboys.band"

START_MARKER = "<!-- JSON-LD:MUSICEVENT:START — generated by tools/events-to-jsonld.py — do not edit -->"
END_MARKER = "<!-- JSON-LD:MUSICEVENT:END -->"


def load_json(path):
    with path.open() as f:
        return json.load(f)


def parse_time(time_str):
    """'11:00 AM' -> (11, 0); '8:00 PM' -> (20, 0)."""
    m = re.match(r"^(\d{1,2}):(\d{2})\s*(AM|PM)$", time_str.strip(), re.IGNORECASE)
    if not m:
        raise ValueError(f"Cannot parse time: {time_str!r}")
    hour = int(m.group(1)) % 12
    if m.group(3).upper() == "PM":
        hour += 12
    return hour, int(m.group(2))


def tz_offset_for(d):
    """US Eastern: EDT (-04:00) roughly Mar 8 – Nov 1, EST (-05:00) otherwise.

    Approximation matching the convention documented in CLAUDE.md. Exact DST
    boundaries (2nd Sunday of March, 1st Sunday of November) could be computed,
    but the CLAUDE.md window is close enough for the dates Bolo Boys actually
    plays.
    """
    if (d.month, d.day) >= (3, 8) and (d.month, d.day) < (11, 2):
        return "-04:00"
    return "-05:00"


def iso_dt(d, hour, minute):
    return f"{d.isoformat()}T{hour:02d}:{minute:02d}:00{tz_offset_for(d)}"


def parse_address(addr_str):
    """'680 Hamilton Ave SE, Atlanta, GA 30312' -> PostalAddress dict."""
    parts = [p.strip() for p in addr_str.split(",")]
    if len(parts) < 3:
        raise ValueError(f"Cannot parse address: {addr_str!r}")
    street = parts[0]
    city = parts[1]
    # Last part is "GA 30312" — split on whitespace
    state_zip = parts[2].split()
    if len(state_zip) < 2:
        raise ValueError(f"Cannot parse state/zip from: {addr_str!r}")
    state = state_zip[0]
    postal = state_zip[1]
    return {
        "@type": "PostalAddress",
        "streetAddress": street,
        "addressLocality": city,
        "addressRegion": state,
        "postalCode": postal,
        "addressCountry": "US",
    }


def build_event(event, venue, today_iso):
    event_date = date.fromisoformat(event["date"])
    hour, minute = parse_time(event["time"])
    duration = event.get("duration_hours", 2)
    start = iso_dt(event_date, hour, minute)
    # Minute-aware so fractional durations (e.g. 3.5) work, not just whole hours.
    total_minutes = hour * 60 + minute + round(duration * 60)
    end_hour, end_minute = divmod(total_minutes, 60)
    # Handle overflow into next day (e.g. 11 PM + 3 hours)
    end_date = event_date
    while end_hour >= 24:
        end_date = end_date + timedelta(days=1)
        end_hour -= 24
    end = iso_dt(end_date, end_hour, end_minute)

    name = f"Bolo Boys at {event['venue_name']}"
    if event.get("theme"):
        name += f" — {event['theme']}"

    if event.get("poster_url"):
        image = f"{SITE_URL}/{event['poster_url']}"
    else:
        image = f"{SITE_URL}/assets/band-photo.jpg"

    return {
        "@type": "MusicEvent",
        "name": name,
        "description": event["invitation_text"],
        "startDate": start,
        "endDate": end,
        "eventStatus": "https://schema.org/EventScheduled",
        "eventAttendanceMode": "https://schema.org/OfflineEventAttendanceMode",
        "image": image,
        "location": {
            "@type": "Place",
            "name": event["venue_name"],
            "address": parse_address(venue["address"]),
        },
        "organizer": {"@type": "Organization", "name": "Bolo Boys", "url": SITE_URL},
        "performer": {"@type": "MusicGroup", "name": "Bolo Boys", "url": SITE_URL},
        "offers": {
            "@type": "Offer",
            "price": "0",
            "priceCurrency": "USD",
            "availability": "https://schema.org/InStock",
            "url": SITE_URL,
            "validFrom": today_iso,
        },
    }


def render_block(graph):
    """Render the @graph payload as a JSON-LD <script> block matching the existing
    formatting in index.html (2-space indent, top-level fields one per line, but
    organizer/performer/offers collapsed onto a single line each)."""
    lines = ["<script type=\"application/ld+json\">", "  {", "    \"@context\": \"https://schema.org\",", "    \"@graph\": ["]
    for i, ev in enumerate(graph):
        lines.append("      {")
        keys = list(ev.keys())
        for j, k in enumerate(keys):
            v = ev[k]
            comma = "," if j < len(keys) - 1 else ""
            if k in ("organizer", "performer", "offers"):
                lines.append(f"        {json.dumps(k)}: {json.dumps(v, ensure_ascii=False)}{comma}")
            elif k == "location":
                lines.append(f"        \"location\": {{")
                lines.append(f"          \"@type\": \"Place\",")
                lines.append(f"          \"name\": {json.dumps(v['name'], ensure_ascii=False)},")
                lines.append(f"          \"address\": {{")
                addr = v["address"]
                addr_keys = list(addr.keys())
                for ai, ak in enumerate(addr_keys):
                    ac = "," if ai < len(addr_keys) - 1 else ""
                    lines.append(f"            {json.dumps(ak)}: {json.dumps(addr[ak], ensure_ascii=False)}{ac}")
                lines.append(f"          }}")
                lines.append(f"        }}{comma}")
            else:
                lines.append(f"        {json.dumps(k)}: {json.dumps(v, ensure_ascii=False)}{comma}")
        close = "      }" + ("," if i < len(graph) - 1 else "")
        lines.append(close)
    lines.append("    ]")
    lines.append("  }")
    lines.append("  </script>")
    return "\n".join(lines)


def replace_between_markers(html, new_block):
    pattern = re.compile(
        re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER),
        re.DOTALL,
    )
    replacement = f"{START_MARKER}\n  {new_block}\n  {END_MARKER}"
    if not pattern.search(html):
        raise SystemExit(
            f"Could not find JSON-LD markers in index.html.\n"
            f"Expected markers:\n  {START_MARKER}\n  {END_MARKER}"
        )
    return pattern.sub(replacement, html)


def main():
    check_only = "--check" in sys.argv

    events_data = load_json(EVENTS_PATH)
    venues_data = load_json(VENUES_PATH)
    venues_by_id = {v["id"]: v for v in venues_data["venues"]}

    today_iso = date.today().isoformat()
    graph = []
    for ev in events_data["events"]:
        if ev.get("unlisted"):
            continue  # private/anonymized cards render on-site only; never indexed
        venue = venues_by_id.get(ev["venue_id"])
        if not venue:
            raise SystemExit(f"Event {ev['id']!r} references unknown venue_id {ev['venue_id']!r}")
        graph.append(build_event(ev, venue, today_iso))

    new_block = render_block(graph)
    html = INDEX_PATH.read_text()
    updated = replace_between_markers(html, new_block)

    if updated == html:
        print(f"JSON-LD already in sync ({len(graph)} events).")
        return 0

    if check_only:
        print(f"JSON-LD is out of date ({len(graph)} events would be regenerated).")
        return 1

    INDEX_PATH.write_text(updated)
    print(f"Updated {INDEX_PATH.name} with {len(graph)} MusicEvent entries.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
