#!/usr/bin/env python3
"""Generate MusicRecording (+ VideoObject) JSON-LD from band.json → releases[0].

Mirrors tools/events-to-jsonld.py: rewrites the block between the
JSON-LD:RELEASE:START / END markers in index.html. Never hand-edit that block.

Emits nothing but the markers when there is no release, so the file stays valid.

Run via tools/run-propagators.sh after editing data/band.json.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BAND = ROOT / "data" / "band.json"
INDEX = ROOT / "index.html"
SITE = "https://www.boloboys.band"

START = "  <!-- JSON-LD:RELEASE:START — generated by tools/release-to-jsonld.py — do not edit -->"
END = "  <!-- JSON-LD:RELEASE:END -->"


def abs_url(path: str) -> str:
    if not path:
        return ""
    if path.startswith("http"):
        return path
    return f"{SITE}/{path.lstrip('/')}"


def build(rel: dict) -> list:
    """Return the list of JSON-LD objects for this release."""
    blocks = []

    recording = {
        "@context": "https://schema.org",
        "@type": "MusicRecording",
        "@id": f"{SITE}/#release-{rel['id']}",
        "name": rel["title"],
        "byArtist": {"@id": f"{SITE}/#band"},
        "url": f"{SITE}/#release",
        "inLanguage": "en",
    }
    if rel.get("isrc"):
        recording["isrcCode"] = rel["isrc"]
    if rel.get("duration_iso"):
        recording["duration"] = rel["duration_iso"]
    if rel.get("release_date"):
        recording["datePublished"] = rel["release_date"]
    if rel.get("cover"):
        recording["image"] = abs_url(rel["cover"])

    # A Bolo-fied traditional: the recording is ours, the composition is nobody's.
    # recordingOf/MusicComposition is what encodes that distinction for Google.
    if rel.get("type") == "traditional_arrangement" and rel.get("composition_name"):
        recording["recordingOf"] = {
            "@type": "MusicComposition",
            "name": rel["composition_name"],
            "composer": {"@type": "Person", "name": "Traditional"},
        }

    streaming = {k: v for k, v in (rel.get("streaming") or {}).items() if v}
    same_as = list(streaming.values())
    if rel.get("hyperfollow"):
        same_as.append(rel["hyperfollow"])
    if same_as:
        recording["sameAs"] = same_as

    blocks.append(recording)

    video = rel.get("video") or {}
    if video.get("youtube_id"):
        vid = {
            "@context": "https://schema.org",
            "@type": "VideoObject",
            "name": f"{rel['title']} — Bolo Boys (Official Music Video)",
            "embedUrl": f"https://www.youtube.com/embed/{video['youtube_id']}",
            "contentUrl": f"https://www.youtube.com/watch?v={video['youtube_id']}",
            "thumbnailUrl": f"https://i.ytimg.com/vi/{video['youtube_id']}/maxresdefault.jpg",
            "uploadDate": rel.get("release_date"),
            "duration": video.get("duration_iso"),
            "author": {"@id": f"{SITE}/#band"},
            "publisher": {"@id": f"{SITE}/#band"},
            "music": {"@id": f"{SITE}/#release-{rel['id']}"},
        }
        if rel.get("cover"):
            vid["image"] = abs_url(rel["cover"])
        desc_bits = []
        if video.get("credit"):
            desc_bits.append(video["credit"])
        if video.get("featuring"):
            desc_bits.append("Featuring " + ", ".join(video["featuring"]) + ".")
        if desc_bits:
            vid["description"] = " ".join(desc_bits)
        # Premiere that hasn't happened yet is a scheduled broadcast, not a published video.
        if video.get("premiere_datetime_et") and rel.get("status") != "out":
            vid["publication"] = {
                "@type": "BroadcastEvent",
                "isLiveBroadcast": True,
                "startDate": video["premiere_datetime_et"],
            }
        vid = {k: v for k, v in vid.items() if v is not None}
        blocks.append(vid)

    return blocks


def main() -> int:
    rel_list = json.loads(BAND.read_text()).get("releases") or []
    html = INDEX.read_text()

    if START not in html or END not in html:
        print("ERROR: release JSON-LD markers not found in index.html", file=sys.stderr)
        return 1

    if not rel_list:
        body = ""
        print("no releases[] — emitting empty block")
    else:
        rel = rel_list[0]
        blocks = build(rel)
        body = "\n".join(
            '  <script type="application/ld+json">\n'
            + json.dumps(b, indent=2, ensure_ascii=False)
            + "\n  </script>"
            for b in blocks
        )
        types = ", ".join(b["@type"] for b in blocks)
        print(f"release JSON-LD: {rel['title']} → {types}")

    new = START + ("\n" + body if body else "") + "\n" + END
    html = re.sub(
        re.escape(START) + r".*?" + re.escape(END),
        lambda _: new,
        html,
        flags=re.DOTALL,
    )
    INDEX.write_text(html)
    return 0


if __name__ == "__main__":
    sys.exit(main())
